### ISSUE TITLE
Migrated code is using playwright-utils dependency which has been deprecated

### ISSUE THREAD

**Issue by avndwivedi09** [AmadeusITGroup/protractor-to-playwright#35] opened 2022-09-15 22:25 UTC
Automation code having having locators in Protractor are being migrated as 
Protractor locator:
var refreshButton = element(by.id('tci-list-header-refresh'));
Migrated locator:   
var refreshButton = getPage().locator('.ng-app-list-name');

getPage is a fixture of playwright-utils which has been deprecated
https://www.npmjs.com/package/playwright-utils
similarly  all the browser.sleep or browser.wait() are converted into 
await getPage().waitForTimeout(3000) 
await waitCondition(ExpectedConditions.visibilityOf(appPage.uploadButton()), 5000, 'button not found');

All the files have been added with this dependency 
import { getPage, ExpectedConditions, waitCondition } from "../../../playwright-utils";

Do we have a workaround or fix for such conversions?

**Comment by fbasso** [comment] 2022-09-16 07:08
Hi, thanks for reporting !

We don't use the package playwright-utils, in our case, it's just an internal file (https://github.com/AmadeusITGroup/protractor-to-playwright/blob/master/scripts/playwright-utils.ts, which is copied in your converted folder) containing some utilities in order to easy / simplify the migration.

The setPage / getPage are utilities in order to reproduce the same behavior as Protractor : the browser is available everywhere. Without these methods, the Playwright `page` should have been propagated in all files / all methods related to the test, rendering the migration much more harder, and potentially with more issues.

**Comment by divdavem** [comment] 2022-10-06 09:54
I am closing this issue because, as @fbasso said, we have no dependency on the deprecated [npm playwright-utils package](https://www.npmjs.com/package/playwright-utils).

**Closed by divdavem** 2022-10-06 09:54 UTC
